logging:
  level:
    root: INFO
    com.workshop.winh: DEBUG
#server:
#   servlet:
#      contextPath: /estrazioni
spring:
   application:
      name: estrazioni-service
   jackson:
      date-format: yyyy-MM-dd
   datasource:
      username: postgres
      password: dev
      # url: jdbc:h2:MEM:testdb
      # driverClassName: org.h2.Driver    
      url: jdbc:postgresql://localhost:5432/estrazioni
      driverClassName: org.postgresql.Driver 
   jpa:
      # database-platform: org.hibernate.dialect.H2Dialect
      database-platform: org.hibernate.dialect.PostgreSQL94Dialect
      # generate-ddl: false
      # hibernate:
      #    ddl-auto: create
   h2:
      console:
         enabled: true
 


management.trace.http.enabled: true
management.endpoints.web.exposure.include: "*,httptrace,prometheus,bindings,streamsbindings"
management.endpoint.health.show-details: always

rest.client.debugEnabled: true